variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-job:
    stage: build
    only:
        - master
    before_script:
        - git submodule sync --recursive
        - git submodule update --init --recursive
    script:
        - make all
